package hk.quantr.riscvstudio.ui;

import hk.quantr.riscvstudio.DummySimulation;
import javax.swing.JPanel;
import javax.swing.table.AbstractTableModel;

public class DataSegmentPanel extends JPanel {

	private static final int COLUMNS = 7;
	private static final int BYTES_PER_ROW = COLUMNS * 4;
	private static final int ROWS = 4;

	private final DummySimulation simulation = DummySimulation.get();
	private final DataTableModel tableModel = new DataTableModel();

	public DataSegmentPanel() {
		initComponents();
		UiDefaults.configureTable(table);
		UiDefaults.setColumnWidths(table, 90, 72, 72, 72, 72, 72, 72, 72, 140);
		refresh();
	}

	public void refresh() {
		tableModel.fireTableDataChanged();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        table.setModel(tableModel);
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

	private final class DataTableModel extends AbstractTableModel {

		private final String[] columns = {
			"Address", "+0", "+4", "+8", "+C", "+10", "+14", "+18", "ASCII"
		};

		@Override
		public int getRowCount() {
			return ROWS;
		}

		@Override
		public int getColumnCount() {
			return columns.length;
		}

		@Override
		public String getColumnName(int column) {
			return columns[column];
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			int base = rowIndex * BYTES_PER_ROW;
			byte[] memory = simulation.getDataMemory();
			if (columnIndex == 0) {
				return UiDefaults.formatHex(0x00000024L + base);
			}
			if (columnIndex == columns.length - 1) {
				return UiDefaults.ascii(memory, base, BYTES_PER_ROW);
			}
			int offset = base + (columnIndex - 1) * 4;
			if (offset + 3 >= memory.length) {
				return "";
			}
			int word = (memory[offset] & 0xFF)
					| ((memory[offset + 1] & 0xFF) << 8)
					| ((memory[offset + 2] & 0xFF) << 16)
					| ((memory[offset + 3] & 0xFF) << 24);
			return UiDefaults.formatWord(word);
		}
	}
}
