package hk.quantr.riscvstudio.ui;

import hk.quantr.riscvstudio.DummySimulation;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class EditorPanel extends JPanel {

	public EditorPanel() {
		initComponents();
		editor.setText(DummySimulation.SOURCE_TEXT);
		editor.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 13));
		editor.setMargin(new Insets(4, 8, 4, 8));
		scrollPane.setRowHeaderView(new LineNumberGutter(editor));
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        editor.setColumns(80);
        editor.setRows(20);
        editor.setTabSize(8);
        scrollPane.setViewportView(editor);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea editor;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

	private static final class LineNumberGutter extends JPanel implements DocumentListener {

		private final javax.swing.JTextArea editor;

		LineNumberGutter(javax.swing.JTextArea editor) {
			this.editor = editor;
			setFont(editor.getFont());
			setOpaque(true);
			setBackground(new Color(0xF4, 0xF4, 0xF4));
			editor.getDocument().addDocumentListener(this);
			editor.addCaretListener(e -> repaint());
			updateWidth();
		}

		private void updateWidth() {
			int digits = Math.max(2, Integer.toString(Math.max(1, editor.getLineCount())).length());
			FontMetrics metrics = getFontMetrics(getFont());
			setPreferredSize(new Dimension(metrics.charWidth('0') * digits + 16, 0));
			revalidate();
		}

		@Override
		protected void paintComponent(Graphics g) {
			super.paintComponent(g);
			g.setColor(new Color(0xD0, 0xD0, 0xD0));
			g.drawLine(getWidth() - 1, 0, getWidth() - 1, getHeight());
			g.setColor(new Color(0x88, 0x88, 0x88));
			g.setFont(getFont());
			FontMetrics metrics = g.getFontMetrics();
			int lineHeight = metrics.getHeight();
			int startY = editor.getInsets().top + metrics.getAscent();
			int lines = editor.getLineCount();
			for (int line = 0; line < lines; line++) {
				String text = Integer.toString(line + 1);
				int x = getWidth() - 8 - metrics.stringWidth(text);
				int y = startY + line * lineHeight;
				g.drawString(text, x, y);
			}
		}

		@Override
		public void insertUpdate(DocumentEvent e) {
			updateWidth();
			repaint();
		}

		@Override
		public void removeUpdate(DocumentEvent e) {
			updateWidth();
			repaint();
		}

		@Override
		public void changedUpdate(DocumentEvent e) {
			repaint();
		}
	}
}
