package hk.quantr.riscvstudio.ui;

import hk.quantr.riscvstudio.DummySimulation;
import javax.swing.JPanel;

public class MessagesPanel extends JPanel {

	private final DummySimulation simulation = DummySimulation.get();

	public MessagesPanel() {
		initComponents();
		assemblerArea.setFont(UiDefaults.mono());
		linkerArea.setFont(UiDefaults.mono());
		refresh();
	}

	public void refresh() {
		assemblerArea.setText(simulation.getAssemblerLog());
		linkerArea.setText(simulation.getLinkerLog());
		assemblerArea.setCaretPosition(0);
		linkerArea.setCaretPosition(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        assemblerScrollPane = new javax.swing.JScrollPane();
        assemblerArea = new javax.swing.JTextArea();
        linkerScrollPane = new javax.swing.JScrollPane();
        linkerArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        assemblerArea.setEditable(false);
        assemblerScrollPane.setViewportView(assemblerArea);

        tabs.addTab("Assembler", assemblerScrollPane);

        linkerArea.setEditable(false);
        linkerScrollPane.setViewportView(linkerArea);

        tabs.addTab("Linker", linkerScrollPane);

        add(tabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea assemblerArea;
    private javax.swing.JScrollPane assemblerScrollPane;
    private javax.swing.JTextArea linkerArea;
    private javax.swing.JScrollPane linkerScrollPane;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
