package hk.quantr.riscvstudio.ui;

import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class ProjectNavigatorPanel extends JPanel {

	public ProjectNavigatorPanel() {
		initComponents();
		projectTree.setModel(new DefaultTreeModel(projectRoot()));
		navigatorTree.setModel(new DefaultTreeModel(navigatorRoot()));
		expand(projectTree);
		expand(navigatorTree);
		javax.swing.SwingUtilities.invokeLater(() -> split.setDividerLocation(0.55));
	}

	private static DefaultMutableTreeNode projectRoot() {
		DefaultMutableTreeNode root = new DefaultMutableTreeNode("riscv-sim");
		DefaultMutableTreeNode sources = new DefaultMutableTreeNode("Source Files");
		sources.add(new DefaultMutableTreeNode("riscv1.asm"));
		root.add(sources);
		root.add(new DefaultMutableTreeNode("inc"));
		root.add(new DefaultMutableTreeNode("Linker Scripts"));
		root.add(new DefaultMutableTreeNode("Libraries"));
		return root;
	}

	private static DefaultMutableTreeNode navigatorRoot() {
		DefaultMutableTreeNode root = new DefaultMutableTreeNode("Symbols");
		root.add(new DefaultMutableTreeNode("_start"));
		root.add(new DefaultMutableTreeNode("main"));
		root.add(new DefaultMutableTreeNode("loop"));
		root.add(new DefaultMutableTreeNode("msg_hello"));
		root.add(new DefaultMutableTreeNode("msg_exit"));
		return root;
	}

	private static void expand(JTree tree) {
		tree.setRootVisible(true);
		for (int i = 0; i < tree.getRowCount(); i++) {
			tree.expandRow(i);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        projectsPanel = new javax.swing.JPanel();
        projectsScrollPane = new javax.swing.JScrollPane();
        projectTree = new javax.swing.JTree();
        navigatorPanel = new javax.swing.JPanel();
        navigatorScrollPane = new javax.swing.JScrollPane();
        navigatorTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        split.setBorder(null);
        split.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        split.setResizeWeight(0.55);

        projectsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Projects"));
        projectsPanel.setLayout(new java.awt.BorderLayout());
        projectsScrollPane.setViewportView(projectTree);
        projectsPanel.add(projectsScrollPane, java.awt.BorderLayout.CENTER);

        split.setLeftComponent(projectsPanel);

        navigatorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigator"));
        navigatorPanel.setLayout(new java.awt.BorderLayout());
        navigatorScrollPane.setViewportView(navigatorTree);
        navigatorPanel.add(navigatorScrollPane, java.awt.BorderLayout.CENTER);

        split.setRightComponent(navigatorPanel);

        add(split, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel navigatorPanel;
    private javax.swing.JScrollPane navigatorScrollPane;
    private javax.swing.JTree navigatorTree;
    private javax.swing.JTree projectTree;
    private javax.swing.JPanel projectsPanel;
    private javax.swing.JScrollPane projectsScrollPane;
    private javax.swing.JSplitPane split;
    // End of variables declaration//GEN-END:variables
}
