package hk.quantr.riscvstudio.ui;

import hk.quantr.riscvstudio.DummySimulation;
import hk.quantr.riscvstudio.DummySimulation.Breakpoint;
import javax.swing.JPanel;
import javax.swing.table.AbstractTableModel;

public class RegistersPanel extends JPanel {

	private final DummySimulation simulation = DummySimulation.get();
	private final RegisterTableModel gprModel = new RegisterTableModel(false);
	private final RegisterTableModel fprModel = new RegisterTableModel(true);
	private final BreakpointTableModel breakpointModel = new BreakpointTableModel();

	public RegistersPanel() {
		initComponents();
		UiDefaults.configureTable(gprTable);
		UiDefaults.configureTable(fprTable);
		UiDefaults.configureTable(breakpointTable);
		UiDefaults.setColumnWidths(gprTable, 70, 70, 110, 110);
		UiDefaults.setColumnWidths(fprTable, 70, 70, 110, 110);
		UiDefaults.setColumnWidths(breakpointTable, 110, 70);
		pcField.setFont(UiDefaults.mono());
		nextPcField.setFont(UiDefaults.mono());
		instrField.setFont(UiDefaults.mono());
		cycleField.setFont(UiDefaults.mono());
		timeField.setFont(UiDefaults.mono());
		privilegeField.setFont(UiDefaults.mono());
		trapField.setFont(UiDefaults.mono());
		isaField.setFont(UiDefaults.mono());
		endianField.setFont(UiDefaults.mono());
		javax.swing.SwingUtilities.invokeLater(() -> split.setDividerLocation(0.55));
		refresh();
	}

	public void refresh() {
		gprModel.fireTableDataChanged();
		fprModel.fireTableDataChanged();
		breakpointModel.fireTableDataChanged();
		pcField.setText(UiDefaults.formatHex(simulation.getPc()));
		nextPcField.setText(UiDefaults.formatHex(simulation.getNextPc()));
		instrField.setText(Long.toString(simulation.getInstructionCount()));
		cycleField.setText(Long.toString(simulation.getCycleCount()));
		timeField.setText(simulation.getTimeNs() + " ns");
		privilegeField.setText("M");
		trapField.setText("0x00000000");
		isaField.setText("RV32I");
		endianField.setText("Little");
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        split = new javax.swing.JSplitPane();
        registerTabs = new javax.swing.JTabbedPane();
        gprScrollPane = new javax.swing.JScrollPane();
        gprTable = new javax.swing.JTable();
        fprScrollPane = new javax.swing.JScrollPane();
        fprTable = new javax.swing.JTable();
        rightSplit = new javax.swing.JSplitPane();
        executionPanel = new javax.swing.JPanel();
        pcLabel = new javax.swing.JLabel();
        pcField = new javax.swing.JTextField();
        nextPcLabel = new javax.swing.JLabel();
        nextPcField = new javax.swing.JTextField();
        instrLabel = new javax.swing.JLabel();
        instrField = new javax.swing.JTextField();
        cycleLabel = new javax.swing.JLabel();
        cycleField = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        privilegeLabel = new javax.swing.JLabel();
        privilegeField = new javax.swing.JTextField();
        trapLabel = new javax.swing.JLabel();
        trapField = new javax.swing.JTextField();
        isaLabel = new javax.swing.JLabel();
        isaField = new javax.swing.JTextField();
        endianLabel = new javax.swing.JLabel();
        endianField = new javax.swing.JTextField();
        breakpointsPanel = new javax.swing.JPanel();
        breakpointScrollPane = new javax.swing.JScrollPane();
        breakpointTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        split.setResizeWeight(0.55);

        gprTable.setModel(gprModel);
        gprScrollPane.setViewportView(gprTable);

        registerTabs.addTab("Registers", gprScrollPane);

        fprTable.setModel(fprModel);
        fprScrollPane.setViewportView(fprTable);

        registerTabs.addTab("Floating Point Registers", fprScrollPane);

        split.setLeftComponent(registerTabs);

        rightSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        rightSplit.setResizeWeight(0.72);
        rightSplit.setMinimumSize(new java.awt.Dimension(210, 120));
        rightSplit.setPreferredSize(new java.awt.Dimension(230, 200));

        executionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Execution State"));
        executionPanel.setLayout(new java.awt.GridBagLayout());

        pcLabel.setText("PC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(pcLabel, gridBagConstraints);

        pcField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(pcField, gridBagConstraints);

        nextPcLabel.setText("Next PC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(nextPcLabel, gridBagConstraints);

        nextPcField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(nextPcField, gridBagConstraints);

        instrLabel.setText("Instrct");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(instrLabel, gridBagConstraints);

        instrField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(instrField, gridBagConstraints);

        cycleLabel.setText("Cycle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(cycleLabel, gridBagConstraints);

        cycleField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(cycleField, gridBagConstraints);

        timeLabel.setText("Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(timeLabel, gridBagConstraints);

        timeField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(timeField, gridBagConstraints);

        privilegeLabel.setText("Privilege Mode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(privilegeLabel, gridBagConstraints);

        privilegeField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(privilegeField, gridBagConstraints);

        trapLabel.setText("Trap Vector");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(trapLabel, gridBagConstraints);

        trapField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(trapField, gridBagConstraints);

        isaLabel.setText("ISA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(isaLabel, gridBagConstraints);

        isaField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(isaField, gridBagConstraints);

        endianLabel.setText("Endian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 8);
        executionPanel.add(endianLabel, gridBagConstraints);

        endianField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 4);
        executionPanel.add(endianField, gridBagConstraints);

        rightSplit.setLeftComponent(executionPanel);

        breakpointsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Breakpoints"));
        breakpointsPanel.setLayout(new java.awt.BorderLayout());

        breakpointTable.setModel(breakpointModel);
        breakpointScrollPane.setViewportView(breakpointTable);

        breakpointsPanel.add(breakpointScrollPane, java.awt.BorderLayout.CENTER);

        rightSplit.setRightComponent(breakpointsPanel);

        split.setRightComponent(rightSplit);

        add(split, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane breakpointScrollPane;
    private javax.swing.JTable breakpointTable;
    private javax.swing.JPanel breakpointsPanel;
    private javax.swing.JTextField cycleField;
    private javax.swing.JLabel cycleLabel;
    private javax.swing.JTextField endianField;
    private javax.swing.JLabel endianLabel;
    private javax.swing.JPanel executionPanel;
    private javax.swing.JScrollPane fprScrollPane;
    private javax.swing.JTable fprTable;
    private javax.swing.JScrollPane gprScrollPane;
    private javax.swing.JTable gprTable;
    private javax.swing.JTextField instrField;
    private javax.swing.JLabel instrLabel;
    private javax.swing.JTextField isaField;
    private javax.swing.JLabel isaLabel;
    private javax.swing.JTextField nextPcField;
    private javax.swing.JLabel nextPcLabel;
    private javax.swing.JTextField pcField;
    private javax.swing.JLabel pcLabel;
    private javax.swing.JTextField privilegeField;
    private javax.swing.JLabel privilegeLabel;
    private javax.swing.JTabbedPane registerTabs;
    private javax.swing.JSplitPane rightSplit;
    private javax.swing.JSplitPane split;
    private javax.swing.JTextField timeField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField trapField;
    private javax.swing.JLabel trapLabel;
    // End of variables declaration//GEN-END:variables

	private final class RegisterTableModel extends AbstractTableModel {

		private final boolean floating;
		private final String[] columns = {"Register", "Name", "Value (Hex)", "Value (Decimal)"};

		RegisterTableModel(boolean floating) {
			this.floating = floating;
		}

		@Override
		public int getRowCount() {
			return 32;
		}

		@Override
		public int getColumnCount() {
			return columns.length;
		}

		@Override
		public String getColumnName(int column) {
			return columns[column];
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			long value = floating ? simulation.getFregisters()[rowIndex] : simulation.getRegisters()[rowIndex];
			return switch (columnIndex) {
				case 0 -> floating ? "f" + rowIndex : "x" + rowIndex;
				case 1 -> floating ? "f" + rowIndex : DummySimulation.ABI_NAMES[rowIndex];
				case 2 -> UiDefaults.formatHex(value);
				case 3 -> Long.toString(value);
				default -> "";
			};
		}
	}

	private final class BreakpointTableModel extends AbstractTableModel {

		private final String[] columns = {"Address", "Enabled"};

		@Override
		public int getRowCount() {
			return simulation.getBreakpoints().size();
		}

		@Override
		public int getColumnCount() {
			return columns.length;
		}

		@Override
		public String getColumnName(int column) {
			return columns[column];
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			Breakpoint breakpoint = simulation.getBreakpoints().get(rowIndex);
			return columnIndex == 0 ? UiDefaults.formatHex(breakpoint.address) : breakpoint.enabled;
		}
	}
}
