package hk.quantr.riscvstudio.ui;

import hk.quantr.riscvstudio.DummySimulation;
import hk.quantr.riscvstudio.DummySimulation.Breakpoint;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;

public class SimulatorPanel extends JPanel {

	private final DummySimulation simulation = DummySimulation.get();
	private final DefaultListModel<String> breakpointModel = new DefaultListModel<>();

	public SimulatorPanel() {
		initComponents();
		breakpointList.setFont(UiDefaults.mono());
		breakpointList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		outputArea.setFont(UiDefaults.mono());
		inputField.setFont(UiDefaults.mono());
		refresh();
	}

	public void refresh() {
		breakpointModel.clear();
		for (Breakpoint breakpoint : simulation.getBreakpoints()) {
			breakpointModel.addElement(String.format("%s  %s",
					breakpoint.enabled ? "[x]" : "[ ]",
					UiDefaults.formatHex(breakpoint.address)));
		}
		outputArea.setText(simulation.getIoOutput());
		outputArea.setCaretPosition(outputArea.getDocument().getLength());
		speedSlider.setValue(simulation.getSpeed());
		runButton.setEnabled(!simulation.isRunning() && !simulation.isHalted());
		pauseButton.setEnabled(simulation.isRunning());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlsPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        assembleButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stepIntoButton = new javax.swing.JButton();
        stepOverButton = new javax.swing.JButton();
        stepOutButton = new javax.swing.JButton();
        speedPanel = new javax.swing.JPanel();
        speedLabel = new javax.swing.JLabel();
        speedSlider = new javax.swing.JSlider();
        speedLabelsPanel = new javax.swing.JPanel();
        minLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        mainSplit = new javax.swing.JSplitPane();
        breakpointsPanel = new javax.swing.JPanel();
        breakpointScrollPane = new javax.swing.JScrollPane();
        breakpointList = new javax.swing.JList<>();
        breakpointTools = new javax.swing.JPanel();
        addBreakpointButton = new javax.swing.JButton();
        removeBreakpointButton = new javax.swing.JButton();
        ioPanel = new javax.swing.JPanel();
        ioTabs = new javax.swing.JTabbedPane();
        outputPanel = new javax.swing.JPanel();
        outputScrollPane = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        outputTools = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new java.awt.BorderLayout(0, 6));

        controlsPanel.setLayout(new java.awt.BorderLayout(0, 4));

        buttonsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        assembleButton.setText("Assemble");
        assembleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assembleButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(assembleButton);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(resetButton);

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(runButton);

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(pauseButton);

        stepIntoButton.setText("Step Into");
        stepIntoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepIntoButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(stepIntoButton);

        stepOverButton.setText("Step Over");
        stepOverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepOverButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(stepOverButton);

        stepOutButton.setText("Step Out");
        stepOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepOutButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(stepOutButton);

        controlsPanel.add(buttonsPanel, java.awt.BorderLayout.CENTER);

        speedPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 4, 0));
        speedPanel.setLayout(new java.awt.BorderLayout(0, 2));

        speedLabel.setText("Run Speed");
        speedPanel.add(speedLabel, java.awt.BorderLayout.PAGE_START);

        speedSlider.setValue(40);
        speedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                speedSliderStateChanged(evt);
            }
        });
        speedPanel.add(speedSlider, java.awt.BorderLayout.CENTER);

        speedLabelsPanel.setLayout(new java.awt.BorderLayout());

        minLabel.setText("Min");
        speedLabelsPanel.add(minLabel, java.awt.BorderLayout.WEST);

        maxLabel.setText("Max (no interaction)");
        speedLabelsPanel.add(maxLabel, java.awt.BorderLayout.EAST);

        speedPanel.add(speedLabelsPanel, java.awt.BorderLayout.PAGE_END);

        controlsPanel.add(speedPanel, java.awt.BorderLayout.PAGE_END);

        add(controlsPanel, java.awt.BorderLayout.PAGE_START);

        mainSplit.setBorder(null);
        mainSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplit.setResizeWeight(0.45);

        breakpointsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Breakpoints"));
        breakpointsPanel.setLayout(new java.awt.BorderLayout(0, 4));

        breakpointList.setModel(breakpointModel);
        breakpointList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breakpointListMouseClicked(evt);
            }
        });
        breakpointScrollPane.setViewportView(breakpointList);

        breakpointsPanel.add(breakpointScrollPane, java.awt.BorderLayout.CENTER);

        breakpointTools.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        addBreakpointButton.setText("+");
        addBreakpointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBreakpointButtonActionPerformed(evt);
            }
        });
        breakpointTools.add(addBreakpointButton);

        removeBreakpointButton.setText("-");
        removeBreakpointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBreakpointButtonActionPerformed(evt);
            }
        });
        breakpointTools.add(removeBreakpointButton);

        breakpointsPanel.add(breakpointTools, java.awt.BorderLayout.PAGE_END);

        mainSplit.setLeftComponent(breakpointsPanel);

        ioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("I/O Console"));
        ioPanel.setPreferredSize(new java.awt.Dimension(200, 160));
        ioPanel.setLayout(new java.awt.BorderLayout());

        outputPanel.setLayout(new java.awt.BorderLayout(0, 4));

        outputArea.setEditable(false);
        outputArea.setLineWrap(true);
        outputScrollPane.setViewportView(outputArea);

        outputPanel.add(outputScrollPane, java.awt.BorderLayout.CENTER);

        outputTools.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        outputTools.add(clearButton);

        outputPanel.add(outputTools, java.awt.BorderLayout.PAGE_END);

        ioTabs.addTab("Output", outputPanel);

        inputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        inputPanel.setLayout(new java.awt.BorderLayout(4, 4));

        inputLabel.setText("stdin");
        inputPanel.add(inputLabel, java.awt.BorderLayout.PAGE_START);
        inputPanel.add(inputField, java.awt.BorderLayout.CENTER);

        ioTabs.addTab("Input", inputPanel);

        ioPanel.add(ioTabs, java.awt.BorderLayout.CENTER);

        mainSplit.setRightComponent(ioPanel);

        add(mainSplit, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void assembleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assembleButtonActionPerformed
        simulation.assemble();
    }//GEN-LAST:event_assembleButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        simulation.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        simulation.run();
    }//GEN-LAST:event_runButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        simulation.pause();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void stepIntoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepIntoButtonActionPerformed
        simulation.stepInto();
    }//GEN-LAST:event_stepIntoButtonActionPerformed

    private void stepOverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepOverButtonActionPerformed
        simulation.stepOver();
    }//GEN-LAST:event_stepOverButtonActionPerformed

    private void stepOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepOutButtonActionPerformed
        simulation.stepOut();
    }//GEN-LAST:event_stepOutButtonActionPerformed

    private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_speedSliderStateChanged
        if (!speedSlider.getValueIsAdjusting()) {
            simulation.setSpeed(speedSlider.getValue());
        }
    }//GEN-LAST:event_speedSliderStateChanged

    private void breakpointListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breakpointListMouseClicked
        if (evt.getClickCount() == 2) {
            simulation.toggleBreakpoint(breakpointList.getSelectedIndex());
        }
    }//GEN-LAST:event_breakpointListMouseClicked

    private void addBreakpointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBreakpointButtonActionPerformed
        simulation.addBreakpoint(0x0000001CL);
    }//GEN-LAST:event_addBreakpointButtonActionPerformed

    private void removeBreakpointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBreakpointButtonActionPerformed
        simulation.removeBreakpoint(breakpointList.getSelectedIndex());
    }//GEN-LAST:event_removeBreakpointButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        simulation.clearIo();
    }//GEN-LAST:event_clearButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBreakpointButton;
    private javax.swing.JButton assembleButton;
    private javax.swing.JList<String> breakpointList;
    private javax.swing.JScrollPane breakpointScrollPane;
    private javax.swing.JPanel breakpointTools;
    private javax.swing.JPanel breakpointsPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel ioPanel;
    private javax.swing.JTabbedPane ioTabs;
    private javax.swing.JSplitPane mainSplit;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JLabel minLabel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JPanel outputTools;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton removeBreakpointButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JPanel speedLabelsPanel;
    private javax.swing.JPanel speedPanel;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton stepIntoButton;
    private javax.swing.JButton stepOutButton;
    private javax.swing.JButton stepOverButton;
    // End of variables declaration//GEN-END:variables
}
