package hk.quantr.riscvstudio.ui;

import hk.quantr.riscvstudio.DummySimulation;
import hk.quantr.riscvstudio.DummySimulation.TextRow;
import javax.swing.JPanel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;

public class TextSegmentPanel extends JPanel {

	private final DummySimulation simulation = DummySimulation.get();
	private final TextTableModel tableModel = new TextTableModel();

	public TextSegmentPanel() {
		initComponents();
		UiDefaults.configureTable(table);
		TableCellRenderer renderer = UiDefaults.pcRenderer(0, simulation::getPc);
		for (int i = 0; i < tableModel.getColumnCount(); i++) {
			table.getColumnModel().getColumn(i).setCellRenderer(renderer);
		}
		UiDefaults.setColumnWidths(table, 100, 100, 180, 200);
		refresh();
	}

	public void refresh() {
		tableModel.fireTableDataChanged();
		int row = simulation.getPcRow();
		if (row >= 0) {
			table.clearSelection();
			table.scrollRectToVisible(table.getCellRect(row, 0, true));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        table.setModel(tableModel);
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

	private final class TextTableModel extends AbstractTableModel {

		private final String[] columns = {"Address", "Code", "Disassembly", "Source"};

		@Override
		public int getRowCount() {
			return simulation.getTextSegment().size();
		}

		@Override
		public int getColumnCount() {
			return columns.length;
		}

		@Override
		public String getColumnName(int column) {
			return columns[column];
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			TextRow row = simulation.getTextSegment().get(rowIndex);
			return switch (columnIndex) {
				case 0 -> UiDefaults.formatHex(row.address);
				case 1 -> UiDefaults.formatWord(row.code);
				case 2 -> row.disassembly;
				case 3 -> row.source;
				default -> "";
			};
		}
	}
}
